import "@/app/globals.css";
import IntegationFooter from "../components/IntegationFooter/IntegationFooter";

export const metadata = {
  title: "ClickUp™ | Integrations",
  description: "Generated by Next.js",
  icons: ["/images/tablogo.svg"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <IntegationFooter />
      </body>
    </html>
  );
}
