import FeatureOrganize from "@/app/components/FeatureOrganize/FeatureOrganize";
import TaskContextbox from "@/app/components/TaskContextbox/TaskContextbox";
import React from "react";
import TaskFeatureTwo from "@/app/components/TaskFeatureTwo/TaskFeatureTwo";
import Featuretask from "@/app/components/Featuretask/Featuretask";

export const metadata = {
  title: "Managing Tasks with ClickUp™",
  description: "Generated by Next.js",
  icons: ["/images/tablogo.svg"],
};

const page = () => {
  return (
    <>
      <Featuretask />
      <TaskContextbox />
      <FeatureOrganize />
      <TaskFeatureTwo />
    </>
  );
};

export default page;
