import "@/app/globals.css";

export const metadata = {
  title: "ClickUp",
  description: "Generated by Next.js",
  icons: ["/images/clicklogo.svg"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
